id: A00C922F4
title: Empowerments of the Eight Symbols, Eight Substances and Seven Emblems
type: translation
pechas:
- I955AEE17
- IFDCFCD07
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:10:35.549914
  last_modified_at: 2023-01-04 12:10:35.549923
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I955AEE17/A50B: 9A6B
  IFDCFCD07/5163: 9A6B
